### PR TITLE
Andres test2

### PR DESCRIPTION
**Pull request by ARam2142**
The about page is ready to be submitted. The contributors section is now listed in alphabetical order by first name.

### CODE REVIEW

**Review by hilbug — CHANGES_REQUESTED** [review]
Hey Andres-
Two thoughts on this:

- Since the About page will be external facing to anyone visiting the site, not just users logged in, let's remove it from the switch statement where it is a private route and remove the link from the subnav.
- Let's add it as Link to the Navbar instead; work with Kayla on where to place it.

Any questions let me know! Thanks, Hilary
- I think i

**Comment by hilbug** [comment]
@kdunphe @ARam2142 @LivesInRoom29 I made a few changes:

- Moved About of Nabar and uncommented out the text on the Landing page
- I updated the text of the About page to include the psychology blurb we had our in group document
- Underlined the link to the About page on the Landing page

**Review by kdunphe — APPROVED** [review]
Looks good

**Review by hilbug — APPROVED** [review]

**Comment by hilbug** [comment]
Kayla and I reviewed changes together and both approved in GitHub.

**Pull request merged**
